name: Go

on: [push]

jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go 1.22
              uses: actions/setup-go@v4
              with:
                go-version: '1.22'
            - name: Check version
              run: go version

