name: Go

on:
  push:
    branches:
      - '*'
    
jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod tidy

      - name: Start Go tests
        run: go test -v ./...

  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Check version
        run: go version && go mod tidy

      - name: prepare for build
        run: go env -w GOOS=windows GOARCH=amd64

      - name: Build
        run: go build -o app.exe cmd/main.go 

      - name: Upload Go build results
        uses: actions/upload-artifact@v4
        with:
          name: Go-build
          path: app.exe
