name: Go

on:
  push:
    branches:
      - '*'
    

jobs:
  build-windows:
    test:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: go mod tidy
        - name: Start Go tests
          run: go test -v ./...
    deploy:
      runs-on: windows-latest
       - uses: actions/checkout@v4
            - name: Setup Go 1.22
              uses: actions/setup-go@v4
              with:
                go-version: '1.22'
            - name: Check version
              run: go version && go mod tidy
            - name: prepare for build
              run: go env -w GOOS=windows GOARCH=amd64
            - name: Build
              run: go build -o app.exe \cmd\main.go 
            - name: Upload Go build results
              uses: actions/upload-artifact@v4
              with:
                name: Go-build
                path: app.exe
  build-rpm:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go 1.22
              uses: actions/setup-go@v4
              with:
                go-version: '1.22'
            - name: Check version
              run: go version && go mod tidy
            - name: Build
              run: go build -v ./...
            - name: Prepare tar-gz
              run: git archive --format=tar.gz --prefix=calc-1.0/ -o calc-1.0.tar.gz HEAD
            - name: make rpm tree
              run: rpmdev-setuptree
            - name: mv app to rpm tree root
              run: mv calc-1.0.tar.gz ~/rpmbuild/SOURCES
            - name: build rpm pack
              run: rpmbuild -ba fedora.spec
            - name: upload Go build results
              uses: actions/upload-artifact@v4
              with:
                name: Go-build
                path: ~/rpmbuild/RPMS/x86_64/calc-1.0-1.fc39.x86_64.rpm
    test:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: go mod tidy
        - name: Start Go tests
          run: go test -v ./...




